sudo: false
dist: trusty

jobs:
  include:
    - stage: Install
      script: scripts/install
    - stage: Unit Tests
      script: scripts/test_unit
    - stage: Integration Tests
      script: scripts/test_integration
