sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo unit tests pass
    - stage: integration tests
      script: echo integration tests pass
    - stage: acceptance tests
      script: echo acceptance tests fail && false
    - stage: deploy the apps
      script: echo Apps deployed
